name: Pool Occupancy Tracker

on:
  schedule:
    - cron: '*/10 4-19 * * *'  # Run every 10 minutes between 6:00-21:59 Prague daylight saving time

jobs:
  track-occupancy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
    
    - name: Run pool tracker
      run: python occupancy.py
    
    - name: Commit and push if changed
      run: |
        if [[ -n $(git status -s) ]]; then
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git add data/pool_occupancy.csv
          git commit -m "Update pool occupancy data"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
