name: Pool Occupancy Tracker

on:
  schedule:
    - cron: '*/10 6-22 * * *'  # Run every 10 minutes between 6:00-22:00 UTC

jobs:
  track-occupancy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Run pool tracker
      run: python occupancy.py
